FROM python:3.10-slim

WORKDIR /app

# Copy requirements from root context (where docker-compose is run)

COPY requirements.txt .

# Install the dependencies inside the image
RUN pip install --no-cache-dir -r requirements.txt
# Copy entire project to container (adjust if needed)
COPY . .

COPY ml-models/. /app/ml-models/.

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
